apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-data
  labels:
    name: nfs-data
spec:
  capacity:
    storage: 1
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /data/gerbau
    server: 192.168.39.1
    #    path: /mnt/data
    #    server: 192.168.1.98
