apiVersion: apps/v1
kind: Deployment
metadata:
  name: busybox
spec:
  template:
    spec:
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: nfs-data-claim-prod
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-data-claim-prod
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1
  storageClassName: nfs
  selector:
    matchLabels:
      name: "nfs-data-prod"
